AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: nodejs20.x
    MemorySize: 512
    Timeout: 30                  # seconds

Resources:
  AuthApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/lambda.handler
      CodeUri: .
      Description: "Express auth API on Lambda"
      VpcConfig:
        SubnetIds:
          - subnet-025ca479540052e08
          - subnet-08d147c171fd26b46
          - subnet-032d4e6b09502491d
        SecurityGroupIds:
          - sg-0b1a154dded1995dc           # the SG that allows outbound to RDS port 3306
      Environment:
        Variables:
          DB_HOST:      database-1.cxqm088cimpr.us-east-2.rds.amazonaws.com
          DB_USER:      admin
          DB_PASS:      P255W0Rd1432
          DB_NAME:      userdb
          JWT_SECRET:   137a1e4c8ab5ae6045b4971f3a977d7f63549e7463d7e571194040e2414389d2
          TWILIO_ACCOUNT_SID: AC1e2b1885fdec29d3333a81c193150fe6
          TWILIO_AUTH_TOKEN:  e57e33c04c7c845ff54b9d9a6dbdf493
          TWILIO_FROM:  +17049303938
          APP_ENV:      dev
          LOG_LEVEL:   debug
      Events:
        ProxyApi:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

Outputs:
  ApiUrl:
    Description: "Base URL for API"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
